all:
	g++ -o meeting3_problem2 meeting3_problem2.cpp

dump:
	objdump -d meeting3_problem2 > meeting3_problem2.asm

clean:
	rm -f meeting3_problem2.o meeting3_problem2

run: meeting3_problem2
	./meeting3_problem2
