all:
	g++ -o meeting6_problem1 meeting6_problem1.cpp

dump:
	objdump -d meeting6_problem1 > meeting6_problem1.asm

clean:
	rm -f meeting6_problem1.o meeting6_problem1

run: meeting6_problem1
	./meeting6_problem1
