all:
	g++ -o meeting4_problem1 meeting4_problem1.cpp

dump:
	objdump -d meeting4_problem1 > meeting4_problem1.asm

clean:
	rm -f meeting4_problem1.o meeting4_problem1

run: meeting4_problem1
	./meeting4_problem1
