all:
	g++ -o problem2_quadratic problem2_quadratic.cpp

dump:
	objdump -d problem2_quadratic > problem2_quadratic.asm

clean:
	rm -f problem2_quadratic.o problem2_quadratic

run: problem2_quadratic
	./problem2_quadratic
