all:
	g++ -o meeting5_problem1 meeting5_problem1.cpp

dump:
	objdump -d meeting5_problem1 > meeting5_problem1.asm

clean:
	rm -f meeting5_problem1.o meeting5_problem1

run: meeting5_problem1
	./meeting5_problem1
