all:
	g++ -o meeting5_problem2 meeting5_problem2.cpp

dump:
	objdump -d meeting5_problem2 > meeting5_problem2.asm

clean:
	rm -f meeting5_problem2.o meeting5_problem2

run: meeting5_problem2
	./meeting5_problem2
