all:
	g++ -o meeting4_problem2 meeting4_problem2.cpp

dump:
	objdump -d meeting4_problem2 > meeting4_problem2.asm

clean:
	rm -f meeting4_problem2.o meeting4_problem2

run: meeting4_problem2
	./meeting4_problem2
