all:
	g++ -o problem 1_payslip problem 1_payslip.cpp

dump:
	objdump -d problem 1_payslip > problem 1_payslip.asm

clean:
	rm -f problem 1_payslip.o problem 1_payslip

run: problem 1_payslip
	./problem 1_payslip
