all:
	g++ -o problem1_payslip problem1_payslip.cpp

dump:
	objdump -d problem1_payslip > problem1_payslip.asm

clean:
	rm -f problem1_payslip.o problem1_payslip

run: problem1_payslip
	./problem1_payslip
