all:
	g++ -o meeting3_problem1 meeting3_problem1.cpp

dump:
	objdump -d meeting3_problem1 > meeting3_problem1.asm

clean:
	rm -f meeting3_problem1.o meeting3_problem1

run: meeting3_problem1
	./meeting3_problem1
