all:
	g++ -o meeting7_problem1 meeting7_problem1.cpp

dump:
	objdump -d meeting7_problem1 > meeting7_problem1.asm

clean:
	rm -f meeting7_problem1.o meeting7_problem1

run: meeting7_problem1
	./meeting7_problem1
