all:
	g++ -o meeting7_problem2 meeting7_problem2.cpp

dump:
	objdump -d meeting7_problem2 > meeting7_problem2.asm

clean:
	rm -f meeting7_problem2.o meeting7_problem2

run: meeting7_problem2
	./meeting7_problem2
