all:
	g++ -o meeting7_problem3 meeting7_problem3.cpp

dump:
	objdump -d meeting7_problem3 > meeting7_problem3.asm

clean:
	rm -f meeting7_problem3.o meeting7_problem3

run: meeting7_problem3
	./meeting7_problem3
